### PR TITLE
Fix the websockets

### PR DESCRIPTION
**Pull request by tdawes**
I literally had 5 minutes to work on something, so decided to pick this up since it's so simple. Technically I haven't tested this but pretty sure it should work :-P

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Someone please test this for Tom?

**Comment by tdawes** [comment]
It does not. One sec.

**Comment by tdawes** [comment]
Hmm
Now it does work....

Can someone else please try this? Probably best to run `yarn clean` before testing

**Comment by andrejak** [comment]
This doesn't seem to work for me, I get an EADDRINUSE error.

**Comment by tdawes** [comment]
Yeah I know the cause - we're spawning two servers (the WS server and the HTTP server) but only error handling one. Going to change how it's done to fix this.

**Comment by tdawes** [comment]
@andrejak this should be working now - am just using [`portfinder`](https://www.npmjs.com/package/portfinder) to start the server instead of our own stuff.

**Pull request merged**
